### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#1]
This package looks very cool, and I’m planning to start using it soon. I was just wondering if you have any guidelines for people interested in contributing to it. I couldn’t find anything about contributing in the README or RTD site, although I might just have missed it. For example, are you open to PRs? If so, do you have a preferred workflow (e.g., open an issue, get feedback, then open the pull request)?

**Comment by bbfrederick** [comment]
Hello!

Great that you want to use the package!  Let me know if you have any questions that the (admittedly limited) docs don’t answer, and I’ll try to help.

Re contributing - um, that’s a great question.  Nobody has every asked to directly contribute before (usually people just send me feature requests and bug reports and I fix them).  And my knowledge of GitHub is barely sufficient to have published the package and update it.  I’m open to pull requests if you are patient enough for me to then figure out how to deal with them…

Blaise

**Comment by tsalo** [comment]
That's great to hear. Would you be willing to add a CONTRIBUTING.md file to the repository? Such files are very useful for people interested in contributing. The STEMMRoleModels repository has a great one you can adjust to your needs [here](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md).
