### ISSUE TITLE
switch to aws mountpoint at some point

### ISSUE THREAD

**Issue by dmd** [bbfrederick/rapidtide#104]
https://github.com/bbfrederick/rapidtide/blob/643dff8b504cd38ea0ec35aaee4438a655b3bce0/cloud/mount-and-run#L34

At some point in the far future we might switch to https://aws.amazon.com/about-aws/whats-new/2023/03/mountpoint-amazon-s3/

**Comment by bbfrederick** [comment]
I defer to you on this - go for it.

**Comment by dmd** [comment]
Not going to do this. Mountpoint doesn't support writing and so we'd have to use s3fs/goofys on the output bucket, and no sense in using both.
