### ISSUE TITLE
Convert scripts to workflows with argparse-based CLI

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#11]
Here is a list of scripts in the package which can be converted to workflows (Python functions with associated, but separate, argument parsers to support command line usage):
 - [ ] [endtidalproc](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/endtidalproc)
- [x] [glmfilt](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/glmfilt)
- [ ] [happy](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/happy)
- [x] [linfit](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/linfit)
- [ ] [rapidtide2](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/rapidtide2)
- [ ] [rapidtide2x](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/rapidtide2x)
- [ ] [showstxcorr](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/showstxcorr)
- [x] [showxcorrx](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/showxcorrx)
- [x] [spatialdecomp](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/spatialdecomp)
- [x] [temporaldecomp](https://github.com/bbfrederick/rapidtide/blob/0abebc7560b5081a575d7f6029dcd9495704b16b/rapidtide/scripts/temporaldecomp)

This issue continues discussion begun in #2. @bbfrederick if there are any scripts that can be dropped or that need to be added, you can probably edit this list directly or, if not, you can add a comment and I'll update it. I can check things off over time as workflows are added.

**Comment by bbfrederick** [comment]
The important ones on the list are showxcorrx (which will become showxcorr when I finally finish testing it), rapidtide2 and rapidtide2x, happy, endtidalproc, and maybe glmfilt, spatialdecomp, temporaldecomp and linfit.

showtc, showxy (basically showanything) are utilities to let you look at things interactively - don't think they are really suited to workflows.  Most of the others are rarely used utillities, with the exception of tidepool, which is a gui viewer program - don't think that really wants to be a workflow either.

**Comment by tsalo** [comment]
Perfect, thank you. I'll drop the extraneous scripts from the checklist and use the checks to track which ones have been successfully converted.

**Comment by bbfrederick** [comment]
This is pretty much done since the 2.0 release.  I'm going to close this.
