### ISSUE TITLE
aligntcs.py index issue

### ISSUE THREAD

**Issue by benalibayram** [bbfrederick/rapidtide#112]
Hi,
It looks like there is an index mismatch here:
https://github.com/bbfrederick/rapidtide/blob/23d007a696d4f5dc7d848286530334f5be6d905d/rapidtide/workflows/aligntcs.py#L111

Adding 1 extends the slice by one more element beyond the length of inputdata1. However, the size of the right-hand side is at the length of inputdata1.

Best regards,
Ali

**Comment by bbfrederick** [comment]
That certainly does look wrong, but it also clearly looks intentional.  I must have had some reason for doing it that way (but perhaps not a valid one!)  I assume this threw an error?
