### ISSUE TITLE
rapidtide hangs

### ISSUE THREAD

**Issue by themeo** [bbfrederick/rapidtide#113]
**Describe the bug**
rapidtide worked on 99% of my datasets, but on one it hangs during/after the first pass. 

I ran the standard LFO noise removal routine from a singularity container:

`singularity exec rapidtide-2.5.7.simg rapidtide {epi} {output} --filterband lfo --passes 3 --nprocs 24 --verbose --debug`

The first output is:
> memprofiler does not exist
> no aggressive optimization
> will not use numba even if present
> setting internal precision to double
> setting output precision to single
> input file is NIFTI
> oversample factor set to 2
> fmri data: 375 timepoints, tr = 1.0, oversamptr = 0.5
> 442330 spatial locations, 375 timepoints
> startpoint set to minimum, (0)
> endppoint set to maximum, ( 374 )
> constructing correlation mask
> generating correlation mask from mean image
> image threshval = 213.46208984375
> validvoxels shape = 168365
> original size = (442330, 375), trimmed size = (168365, 375)
> moving fmri data to shared memory
> constructing global mean signal using sum
> used 442330 voxels to calculate global mean signal
> no regressor file specified - will use the global mean regressor
> using global mean as probe regressor
> Regressor start time, end time, and step: -0.000, 375.000, 1.000
> Input vector
> length: 375
> input freq: 1.0
> input start time: 0.000
> synctime is 0.0
> total probe regressor offset is 0.0
> there are 375 points in the original regressor
> the timepoint spacing is 1.0
> the input timecourse start time is 0.0
> first fMRI point is at 0.0 seconds relative to time origin
> os_fmri_x dim-0 shape: 749
> initial_fmri_x dim-0 shape: 375
> filtering to lfo band
> 749 749 375 375
> corrtr=0.5
> trimmedcorrscale length: 119
> trimmedmiscale length: 0 120
> corrorigin at point 750 0.5
> corr range from 691 (-29.0) to 810 (30.5)
> allocating memory for correlation arrays (442330, 119) (168365, 119)
> setting up fast resampling with padtime = 60.0
> refine is set to True
> edgebufferfrac set to 0.00133422281521014

During first pass, somewhere during/after despeckling subpass 4, it gets progressively slower, and hangs at random points, e.g.:

> maxsigma_init: 1.4863131505040332
> fit input array: [ 0.19456056 27.          1.48631315]
> maxsigma_init: 1.698643600576038
> fit input array: [0.28374144 3.         1.6986436 ]
> maxsigma_init: 2.1233045007200477
> fit input array: [0.28102372 2.         2.1233045 ]
> Voxel:   7%|███████▍                                                                                                   | > 11693/168365 [04:21<33:11, 78.66it/s]

with almost 0 CPU usage. 
I can share the functional file if needed. 

**Desktop (please complete the following information):**

> Linux dccn-c056.dccn.nl 4.19.94-300.el7.x86_64 #1 SMP Thu Jan 9 16:15:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by themeo** [comment]
I already deleted the BOLD file that led to the issue, and when I reassembled it, I could no longer replicate the issue. I will get back here once I encounter the problem again. Sorry for the confusion!

**Comment by bbfrederick** [comment]
No problem.  Glad it's working!
