### ISSUE TITLE
--nofitfilt without effect

### ISSUE THREAD

**Issue by poeplau** [bbfrederick/rapidtide#114]
Hello,

**Description**
The argument --nofitfilt doesn't seem to have an effect. The analysis yielded the same results as without it. It seems to me that it isn't passed properly, because the option "zerooutbadfit" is unused as far as I can see. I managed to fix the problem by including 'zerooutbadfit=optiondict["zerooutbadfit"]' in the options of the initialization of the correlation fitter.

**Comment by bbfrederick** [comment]
Yup, you are correct, about both the problem and the fix.  Whoops!  Fixed in 2.5.8.
