### ISSUE TITLE
Latest version in docker does not run

### ISSUE THREAD

**Issue by dittothat** [bbfrederick/rapidtide#122]
**Describe the bug**
Running the docker version on the demo data causes an error.

```
memprofiler does not exist
no aggressive optimization
will not use numba even if present
Traceback (most recent call last):
  File "/opt/conda/bin/rapidtide", line 23, in <module>
    rapidtide_workflow.rapidtide_main(rapidtide_parser.process_args(inputargs=None))
  File "/opt/conda/lib/python3.11/site-packages/rapidtide/workflows/rapidtide.py", line 352, in rapidtide_main
    optiondict["dockermemfree"], optiondict["dockermemswap"] = tide_util.findavailablemem()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
```
docker run     --mount type=bind,source=OUTPUT/,destination=/data_out     fredericklab/rapidtide:v2.6.2         rapidtide             /src/rapidtide/rapidtide/data/examples/src/sub-RAPIDTIDETEST.nii.gz             /data_out/dgsr             --filterband lfo             --searchrange -15 15             --passes 3
```

**Expected behavior**
Rapidtide runs and gives outputs. As it does for earlier versions

**Additional context**
Docker version 24.0.5, build ced0996 on Ubuntu 20.04.6 LTS

**Comment by bbfrederick** [comment]
That seems to be an incomplete error message - the actual error that triggered the failure would be on a line underneath

optiondict["dockermemfree"], optiondict["dockermemswap"] = tide_util.findavailablemem()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

Can you send the remaining lines?

**Comment by bbfrederick** [comment]
Sometime after 7PM Eastern US Time today (September 12, 2023) when the container finishes building, pull the fredericklab/rapidtide:latest container, and see if it works.

**Comment by dittothat** [comment]
Thank you so much for looking into this and fixing it. Runs now!
