### ISSUE TITLE
tidepool unexpected closed

### ISSUE THREAD

**Issue by Ernest861** [bbfrederick/rapidtide#168]
**Describe the bug**
I tried to use tidepool to show the results after rapidtide.
But after the window opens and loads test_desc-maxtime_map.nii.gz, it displays an error and closes.

WARNING: 1 maps could not be loaded - not enough panes
simfuncFitter has been defined
Traceback (most recent call last):
  File "/Users/macbear/miniforge3/envs/py310/bin/tidepool", line 4, in <module>
    __import__('pkg_resources').run_script('rapidtide==2.9.6', 'tidepool')
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 755, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1733, in run_script
    exec(code, namespace, namespace)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/EGG-INFO/scripts/tidepool", line 23, in <module>
    pf.generic_init(theworkflow._get_parser, theworkflow.tidepool)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/rapidtide/workflows/parser_funcs.py", line 874, in generic_init
    themain(args)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/rapidtide/workflows/tidepool.py", line 2203, in tidepool
    overlay_radioButton_01_clicked(True)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/rapidtide/workflows/tidepool.py", line 1057, in overlay_radioButton_01_clicked
    overlay_radioButton_clicked(0, enabled)
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/rapidtide/workflows/tidepool.py", line 1111, in overlay_radioButton_clicked
    elif overlays[currentdataset.focusmap].lut_state == gen_turbo_state():
  File "/Users/macbear/miniforge3/envs/py310/lib/python3.10/site-packages/rapidtide-2.9.6-py3.10.egg/rapidtide/Colortables.py", line 96, in gen_turbo_state
    return Gradients["turbo"]
KeyError: 'turbo'
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS M2Max
 - Version [14.61]
 - Python [3.9 or 3.10]

conda create --name py310 python=3.10
conda activate py310
conda install numpy scipy pandas pyarrow scikit-image scikit-learn nibabel nilearn matplotlib pyqt5-sip pyqtgraph statsmodels tomlkit tqdm numba pyfftw memory_profiler keras tensorflow
conda nibabel pyqtgraph pyfftw
conda install pyqt5

**Comment by bbfrederick** [comment]
Good catch.  From what I can see here, I think you may have an older version of matplotlib than I was expecting.  The "turbo" colormap was introduced in 3.3.0 (July 2020).  I didn't start using it until April 2024, and I didn't update the requirements to specify 3.3.0 or above (because I didn't think to).

Can you try upgrading matplotlib to 3.3.0 or above and seeing if that fixes the problem?

**Comment by Ernest861** [comment]
Thank you, I think the matplotlib is 3.9.2, I also have try installed 3.8.2, 3.3.0, 3.7.0. 
Same KeyError show.
Might be able to give a set of recommended Python and moudle vesrion requirements.txt
Thank your very much.

**Comment by bbfrederick** [comment]
Interesting - I thought that would work.

I updated the requirements in the latest push to GitHub, that should at least be fixed it going forward, but that would indicate that that wasn't the issue.  The actual call that's failing is to pyqtgraph - what version is that?  Can you send a dump of your environment using "conda list"?

**Comment by Ernest861** [comment]
Thanks for your quickly reply! 
The pyqtgraph is 0.13.1.    
Here is my list: 
# packages in environment at /Users/macbear/miniforge3/envs/py310:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0           py310hca03da5_0  
aom                       3.9.1                h7bae524_0    conda-forge
archspec                  0.2.3              pyhd3eb1b0_0  
astunparse                1.6.3                      py_0  
aws-c-auth                0.7.29               hd3c7522_1    conda-forge
aws-c-cal                 0.7.4                h41dd001_1    conda-forge
aws-c-common              0.9.28               hd74edd7_0    conda-forge
aws-c-compression         0.2.19               h41dd001_1    conda-forge
aws-c-event-stream        0.4.3                hb2a355e_1    conda-forge
aws-c-http                0.8.8                hf5a2c8c_2    conda-forge
aws-c-io                  0.14.18              hc3cb426_9    conda-forge
aws-c-mqtt                0.10.4              hb9beb3e_19    conda-forge
aws-c-s3                  0.6.5                h439c227_2    conda-forge
aws-c-sdkutils            0.1.19               h41dd001_3    conda-forge
aws-checksums             0.1.18              h41dd001_11    conda-forge
aws-crt-cpp               0.28.2               h4756f83_4    conda-forge
aws-sdk-cpp               1.11.379             h67f4a54_9    conda-forge
azure-core-cpp            1.13.0               hd01fc5c_0    conda-forge
azure-identity-cpp        1.8.0                h13ea094_2    conda-forge
azure-storage-blobs-cpp   12.12.0              hfde595f_0    conda-forge
azure-storage-common-cpp  12.7.0               hcf3b6fd_1    conda-forge
azure-storage-files-datalake-cpp 12.11.0              h082e32e_1    conda-forge
blas                      2.123                  openblas    conda-forge
blas-devel                3.9.0           23_osxarm64_openblas    conda-forge
blosc                     1.21.6               h5499902_0    conda-forge
boltons                   23.0.0          py310hca03da5_0  
bottleneck                1.3.7           py310hbda83bc_0  
brotli                    1.1.0                hd74edd7_2    conda-forge
brotli-bin                1.1.0                hd74edd7_2    conda-forge
brotli-python             1.0.9           py310h313beb8_8  
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h80987f9_6  
c-ares                    1.33.1               hd74edd7_0    conda-forge
c-blosc2                  2.14.4               ha57e6be_1    conda-forge
ca-certificates           2024.7.2             hca03da5_0  
cached-property           1.5.2                      py_0  
certifi                   2024.8.30       py310hca03da5_0  
cffi                      1.16.0          py310h80987f9_1  
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.3.2              pyhd3eb1b0_0  
conda                     24.7.1          py310hca03da5_0  
conda-libmamba-solver     24.7.0             pyhd3eb1b0_0  
conda-package-handling    2.3.0           py310hca03da5_0  
conda-package-streaming   0.10.0          py310hca03da5_0  
contourpy                 1.2.0           py310h48ca7d4_0  
cycler                    0.11.0             pyhd3eb1b0_0  
dav1d                     1.2.1                h80987f9_0  
distro                    1.9.0           py310hca03da5_0  
flatbuffers               24.3.25              h313beb8_0  
fmt                       9.1.0                h48ca7d4_1  
fonttools                 4.51.0          py310h80987f9_0  
freetype                  2.12.1               hadb7bae_2    conda-forge
frozendict                2.4.2           py310h80987f9_0  
gast                      0.5.3              pyhd3eb1b0_0  
gflags                    2.2.2                h313beb8_1  
giflib                    5.2.2                h93a5062_0    conda-forge
glog                      0.7.1                heb240a5_0    conda-forge
google-pasta              0.2.0              pyhd3eb1b0_0  
grpcio                    1.62.2          py310hf7687f1_0    conda-forge
h5py                      3.11.0          nompi_py310h92897fd_102    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.7             py310hca03da5_0  
imagecodecs               2024.6.1        py310hfb4dfaf_0    conda-forge
imageio                   2.33.1          py310hca03da5_0  
importlib_resources       6.4.0           py310hca03da5_0  
joblib                    1.4.2           py310hca03da5_0  
jsonpatch                 1.33            py310hca03da5_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jxrlib                    1.1                  h1a28f6b_2  
keras                     3.4.1           py310hca03da5_0  
kiwisolver                1.4.4           py310h313beb8_0  
krb5                      1.21.3               h237132a_0    conda-forge
lazy_loader               0.4             py310hca03da5_0  
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20240116.2      cxx17_h313beb8_0  
libaec                    1.1.3                hebf3989_0    conda-forge
libarchive                3.7.4                h83d404f_0    conda-forge
libarrow                  17.0.0          h77c2f02_14_cpu    conda-forge
libarrow-acero            17.0.0          hf9b8971_14_cpu    conda-forge
libarrow-dataset          17.0.0          hf9b8971_14_cpu    conda-forge
libarrow-substrait        17.0.0          hbf8b706_14_cpu    conda-forge
libavif16                 1.1.1                ha4d98b1_1    conda-forge
libblas                   3.9.0           23_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hd74edd7_2    conda-forge
libbrotlidec              1.1.0                hd74edd7_2    conda-forge
libbrotlienc              1.1.0                hd74edd7_2    conda-forge
libcblas                  3.9.0           23_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hc377ac9_0  
libcurl                   8.10.0               h13a7ad3_0    conda-forge
libcxx                    18.1.8               h3ed4263_7    conda-forge
libdeflate                1.20                 h93a5062_0    conda-forge
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_1  
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libgoogle-cloud           2.29.0               hfa33a2f_0    conda-forge
libgoogle-cloud-storage   2.29.0               h90fd6fa_0    conda-forge
libgrpc                   1.62.2               h9c18a4f_0    conda-forge
libhwy                    1.1.0                h2ffa867_0    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.3                h80987f9_0  
libjxl                    0.10.3               h44ef4fb_0    conda-forge
liblapack                 3.9.0           23_osxarm64_openblas    conda-forge
liblapacke                3.9.0           23_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hd1a9a77_4    conda-forge
libmamba                  1.5.8                haeffa04_3  
libmambapy                1.5.8           py310h1c5506f_3  
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h517c56d_1    conda-forge
libparquet                17.0.0          hf0ba9ef_14_cpu    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
libprotobuf               4.25.3               hbfab5d5_0    conda-forge
libre2-11                 2023.09.01           h7b2c953_2    conda-forge
libsolv                   0.7.30               h6c9b7f8_0    conda-forge
libsqlite                 3.46.1               hc14010f_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.20.0               h64651cc_1    conda-forge
libtiff                   4.6.0                h07db509_3    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.16                 hc9fafa5_1    conda-forge
libxml2                   2.12.7               h01dff8b_4    conda-forge
libxslt                   1.1.39               h223e5b9_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
libzopfli                 1.0.3                hc377ac9_0  
llvm-openmp               18.1.8               hde57baf_1    conda-forge
llvmlite                  0.43.0          py310h313beb8_0  
lxml                      5.3.0           py310hed7ee58_1    conda-forge
lz4-c                     1.9.4                h313beb8_1  
lzo                       2.10                 h1a28f6b_2  
markdown                  3.4.1           py310hca03da5_0  
markdown-it-py            2.2.0           py310hca03da5_1  
markupsafe                2.1.3           py310h80987f9_0  
matplotlib                3.7.0                    pypi_0    pypi
mdurl                     0.1.0           py310hca03da5_0  
memory_profiler           0.58.0             pyhd3eb1b0_0  
menuinst                  2.1.2           py310hca03da5_0  
ml_dtypes                 0.4.0           py310h46d7db6_0  
namex                     0.0.7           py310hca03da5_0  
ncurses                   6.5                  h7bae524_1    conda-forge
networkx                  3.3             py310hca03da5_0  
nibabel                   5.2.1              pyha770c72_0    conda-forge
nilearn                   0.10.4             pyhd8ed1ab_0    conda-forge
numba                     0.60.0          py310h313beb8_0  
numexpr                   2.8.7           py310hecc3335_0  
numpy                     1.26.4          py310h3b2db8e_0  
numpy-base                1.26.4          py310ha9811e2_0  
openblas                  0.3.27          openmp_h560b219_1    conda-forge
openjpeg                  2.5.2                h54b8e55_0  
openssl                   3.3.2                h8359307_0    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1  
optree                    0.12.1          py310h48ca7d4_0  
orc                       2.0.2                h75dedd0_0    conda-forge
packaging                 24.1            py310hca03da5_0  
pandas                    2.2.2           py310h313beb8_0  
patsy                     0.5.6           py310hca03da5_0  
pillow                    10.4.0          py310h383043f_1    conda-forge
pip                       24.2            py310hca03da5_0  
platformdirs              3.10.0          py310hca03da5_0  
pluggy                    1.0.0           py310hca03da5_1  
protobuf                  4.25.3          py310h8472c4a_0  
psutil                    5.9.0           py310h1a28f6b_0  
pthread-stubs             0.3                  h1a28f6b_1  
pyarrow                   17.0.0          py310h24597f5_1    conda-forge
pyarrow-core              17.0.0          py310hf3d4daf_1_cpu    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h80987f9_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyfftw                    0.14.0          py310hb3e58dc_0    conda-forge
pygments                  2.15.1          py310hca03da5_1  
pyparsing                 3.1.2           py310hca03da5_0  
pyqt5                     5.15.11                  pypi_0    pypi
pyqt5-qt5                 5.15.15                  pypi_0    pypi
pyqt5-sip                 12.15.0                  pypi_0    pypi
pyqt6-qt6                 6.7.2                    pypi_0    pypi
pyqt6-sip                 13.8.0                   pypi_0    pypi
pyqtgraph                 0.13.1          py310hca03da5_0  
pysocks                   1.7.1           py310hca03da5_0  
python                    3.10.14         h2469fbe_0_cpython    conda-forge
python-dateutil           2.9.0post0      py310hca03da5_2  
python-flatbuffers        24.3.25         py310hca03da5_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.10                    5_cp310    conda-forge
pytz                      2024.1          py310hca03da5_0  
pywavelets                1.7.0                    pypi_0    pypi
rapidtide                 2.9.6                    pypi_0    pypi
rav1e                     0.6.6                h69fbcac_2    conda-forge
re2                       2023.09.01           h4cba328_2    conda-forge
readline                  8.2                  h1a28f6b_0  
reproc                    14.2.4               h313beb8_2  
reproc-cpp                14.2.4               h313beb8_2  
requests                  2.32.3          py310hca03da5_0  
rich                      13.7.1          py310hca03da5_0  
ruamel.yaml               0.17.21         py310h1a28f6b_0  
ruamel.yaml.clib          0.2.8           py310hd125d64_0    conda-forge
scikit-image              0.23.2          py310h46d7db6_0  
scikit-learn              1.5.1           py310h46d7db6_0  
scipy                     1.13.1          py310hd336fd7_0  
setuptools                72.1.0          py310hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.2.1                h313beb8_0  
statsmodels               0.14.2          py310h80987f9_0  
svt-av1                   2.2.1                ha39b806_0    conda-forge
tbb                       2021.8.0             h48ca7d4_0  
tensorboard               2.17.0          py310hca03da5_0  
tensorboard-data-server   0.7.0           py310ha6e5c4f_1  
tensorflow                2.17.0          cpu_py310hd689282_0    conda-forge
tensorflow-base           2.17.0          cpu_py310hce8bbbd_0    conda-forge
tensorflow-estimator      2.17.0          cpu_py310h85e80fb_0    conda-forge
termcolor                 2.1.0           py310hca03da5_0  
threadpoolctl             3.5.0           py310h33ce5c2_0  
tifffile                  2023.4.12       py310hca03da5_0  
tk                        8.6.13               h5083fa2_1    conda-forge
tomlkit                   0.11.1          py310hca03da5_0  
tornado                   6.4.1           py310h80987f9_0  
tqdm                      4.66.5          py310h33ce5c2_0  
truststore                0.8.0           py310hca03da5_0  
typing-extensions         4.11.0          py310hca03da5_0  
typing_extensions         4.11.0          py310hca03da5_0  
tzdata                    2024a                h04d1e81_0  
unicodedata2              15.1.0          py310h80987f9_0  
urllib3                   2.2.2           py310hca03da5_0  
werkzeug                  3.0.3           py310hca03da5_0  
wheel                     0.44.0          py310hca03da5_0  
wrapt                     1.14.1          py310h1a28f6b_0  
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.4.6                h80987f9_1  
yaml-cpp                  0.8.0                h313beb8_1  
zfp                       1.0.1                ha84d530_1    conda-forge
zlib-ng                   2.0.7                h80987f9_0  
zstandard                 0.23.0          py310h2665a74_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge

**Comment by bbfrederick** [comment]
Ok, now I'm mystified.

Can you do the following?

conda env export > environment_droplet.yml

Then send me the .yml file?  Then I can generate an identical installation here (coincidentally, I too am running macOS on an M2Max :-) ). That should help me figure out what's going on.

**Comment by bbfrederick** [comment]
Actually, first do this:

On the command line, type:

python
from pyqtgraph.graphicsItems.GradientEditorItem import Gradients
print(Gradients)

And send me all the output.

**Comment by Ernest861** [comment]
Ok, here is the output:
`>>> from pyqtgraph.graphicsItems.GradientEditorItem import Gradients`
`>>> print(Gradients)`
OrderedDict([('thermal', {'ticks': [(0.3333, (185, 0, 0, 255)), (0.6666, (255, 220, 0, 255)), (1, (255, 255, 255, 255)), (0, (0, 0, 0, 255))], 'mode': 'rgb'}), ('flame', {'ticks': [(0.2, (7, 0, 220, 255)), (0.5, (236, 0, 134, 255)), (0.8, (246, 246, 0, 255)), (1.0, (255, 255, 255, 255)), (0.0, (0, 0, 0, 255))], 'mode': 'rgb'}), ('yellowy', {'ticks': [(0.0, (0, 0, 0, 255)), (0.2328863796753704, (32, 0, 129, 255)), (0.8362738179251941, (255, 255, 0, 255)), (0.5257586450247, (115, 15, 255, 255)), (1.0, (255, 255, 255, 255))], 'mode': 'rgb'}), ('bipolar', {'ticks': [(0.0, (0, 255, 255, 255)), (1.0, (255, 255, 0, 255)), (0.5, (0, 0, 0, 255)), (0.25, (0, 0, 255, 255)), (0.75, (255, 0, 0, 255))], 'mode': 'rgb'}), ('spectrum', {'ticks': [(1.0, (255, 0, 255, 255)), (0.0, (255, 0, 0, 255))], 'mode': 'hsv'}), ('cyclic', {'ticks': [(0.0, (255, 0, 4, 255)), (1.0, (255, 0, 0, 255))], 'mode': 'hsv'}), ('greyclip', {'ticks': [(0.0, (0, 0, 0, 255)), (0.99, (255, 255, 255, 255)), (1.0, (255, 0, 0, 255))], 'mode': 'rgb'}), ('grey', {'ticks': [(0.0, (0, 0, 0, 255)), (1.0, (255, 255, 255, 255))], 'mode': 'rgb'}), ('viridis', {'ticks': [(0.0, (68, 1, 84, 255)), (0.25, (58, 82, 139, 255)), (0.5, (32, 144, 140, 255)), (0.75, (94, 201, 97, 255)), (1.0, (253, 231, 36, 255))], 'mode': 'rgb'}), ('inferno', {'ticks': [(0.0, (0, 0, 3, 255)), (0.25, (87, 15, 109, 255)), (0.5, (187, 55, 84, 255)), (0.75, (249, 142, 8, 255)), (1.0, (252, 254, 164, 255))], 'mode': 'rgb'}), ('plasma', {'ticks': [(0.0, (12, 7, 134, 255)), (0.25, (126, 3, 167, 255)), (0.5, (203, 71, 119, 255)), (0.75, (248, 149, 64, 255)), (1.0, (239, 248, 33, 255))], 'mode': 'rgb'}), ('magma', {'ticks': [(0.0, (0, 0, 3, 255)), (0.25, (80, 18, 123, 255)), (0.5, (182, 54, 121, 255)), (0.75, (251, 136, 97, 255)), (1.0, (251, 252, 191, 255))], 'mode': 'rgb'})])


The system seem doesn't support the yml file, I compress it.
[environment_droplet.yml.zip](https://github.com/user-attachments/files/17015302/environment_droplet.yml.zip)

**Comment by bbfrederick** [comment]
Ok, turbo was not added to pyqtgraph until 0.13.4 (you have 0.13.1).  So I'm revising the requirements to pyqtgraph>=0.13.4.

Can you try upgrading pyqtgraph and seeing if that fixes it?

**Comment by Ernest861** [comment]
Nice! It works. 
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/237e28ff-e75f-46a4-9dde-cc095bcef99c">
While there is a very complete instruction manual for [rapidtide Documentation] (https://rapidtide.readthedocs.io/_/downloads/en/latest/pdf/), if there is a toturial about how to use and interpret rapidtide results.

**Comment by bbfrederick** [comment]
Great!

The tutorial is definitely lacking at the moment, and I really need to beef up that part of the documentation.  To some extent that's because it depends what you are trying to do - are you looking to remove physiological noise from data to do task or resting state analysis, or are you trying to look at brain hemodynamics?  Depending on your goals, you might go about the analyses differently.

**Comment by Ernest861** [comment]
Thank you for your feedback, this is a migraine patient and my collaborator wants to learn more about the correlation of neural activity. Looking forward to the tutorial on dynamic hemodynamics, I will continue to learn from your work.
