### ISSUE TITLE
ccorrica does not upsample timeseries by default

### ISSUE THREAD

**Issue by irebollo** [bbfrederick/rapidtide#18]
Unlike rapidtide2, ccorrica does not upsample the timeseries to 2 hz. This might be an issue to particularly slow TR 2-2.5s. I'm doing some tests now to determine how much it affects the delayed connectivity values. Updates soon.

**Comment by bbfrederick** [comment]
I've added the ability to upsample the data prior to correlation using the -O OVERSAMPFAC option to specify the integer oversample factor.  Setting OVERSAMPFAC to any negative value will select the lowest integer value that makes the oversampled sample rate at least 2 Hz (i.e. identical behavior to rapidtide2).
