### ISSUE TITLE
A problem with singularity image

### ISSUE THREAD

**Issue by themeo** [bbfrederick/rapidtide#180]
**Describe the bug**
When calling `rapidtide` from within the singularity container, it cannot be found.

**To Reproduce**
I assembled the rapidtide container yesterday using the 'latest' tag (which I presume was 2.9.9.2 version, even though it was not published under its own tag). 
Then I run `singularity exec --cleanenv -B ./:/data_in,./:data_out ./rapidtide-2.9.9.2.simg rapidtide`
and get the following error:
FATAL:   "rapidtide": executable file not found in $PATH

**Comment by bbfrederick** [comment]
Hi,

Sorry for the delay on this - I've been swamped on a grant submission.

I seem to have broken something in a subtle way in my Docker build process.  I used multiple build stages to try to get around time limits for build times on GitHub, and somewhere in the last month something got out of whack, and I'm trying to chase it down.  

I'll see I can set rapidtide back to build off the last known good base container, which would at least be a stopgap.  FWIW, a bare metal install of the newest version of rapidtide does work, so if that's an option for you, you might try it.  But fixing the container thing has moved to the top of the priority list.

**Comment by bbfrederick** [comment]
Well that was an absolute nightmare.  But, fixed!  Give it a whirl.  latest, latest-release, and v2.9.9.5 and up should work now.

**Comment by bbfrederick** [comment]
Closing, but if it doesn't work for you, feel free to reopen.
