### ISSUE TITLE
Sanitize/check LAGMIN and LAGMAX command line inputs

### ISSUE THREAD

**Issue by danlurie** [bbfrederick/rapidtide#19]
I just spent an hour trying to diagnose a crash in `rapidtide2` that turned out to be caused by me forgetting to include a negative sign when specifying LAGMIN. That is to say I did `-r 10,10` instead of `-r -10,10`. This was completely my fault, but it suggests it is probably worth checking the inputs to check that LAGMIN is negative and LAGMAX is positive, and writing a useful error message if this isn't the case. I'm happy to implement this at some point, though I see there is talk about refactoring to use `argparse` so it might be best to just add it in then.

**Comment by bbfrederick** [comment]
Ach - sorry about that - that was a dumb bug.  Should now be fixed in rapiditde2 and 2x

**Comment by danlurie** [comment]
No need to apologize! The main reason the suggestion occurred to me is that I encounter similar issues with my own code on an embarrassingly regular basis.
