### ISSUE TITLE
[FIX] Typos in INSTALL.md

### ISSUE THREAD

**Issue by antotorov** [bbfrederick/rapidtide#22]
Hello
in the Usage section, the first command currently read

`rapidtide2 rapidtide/data/examples/src/fmri.nii.gz rapidtide/data/examples/examples/dst/dgsr -L -r -15,15 --refinepasses=3`

However `rapidtide/data/examples/examples/dst/dgsr` does not exist, and the path should be `rapidtide/data/examples/dst/dgsr`

There's also a typo in the second command: 

`rapidtide2 rapidtide/data/examples/srd/fmri.nii.gz rapidtide/data/examples/dst/sgsr -L -Z 0.0`

The file `rapidtide/data/examples/srd/fmri.nii.gz` does not exist; the correct path is

`rapidtide/data/examples/src/fmri.nii.gz`

Thanks for developing this package!
Best

**Comment by bbfrederick** [comment]
Fixed!  Thank you.
