### ISSUE TITLE
prewhitening

### ISSUE THREAD

**Issue by ZieroNLD** [bbfrederick/rapidtide#28]
Rapidtide2 had the option (experimental though) to perform prewhitening on the date prior to the crosscorrelation, which seems quite sensible considering possible trends etc in the data

I  noticed that the option was not available for the rapidtide2x routine. 
Will this option return, or do you think it is not that useful?

Thanks!

**Comment by bbfrederick** [comment]
I never really found a use for it, so I stopped working on it.  I'll probably fully strip it out of the code at some point.
