### ISSUE TITLE
Automate versioning with versioneer

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#30]
**Is your feature request related to a problem? Please describe.**
It's no problem, but it would be easier to infer the version string if you used versioneer.

**Describe the solution you'd like**
[versioneer](https://github.com/warner/python-versioneer) automatically manages version strings for Python projects. You wouldn't need to write in version strings in any of rapidtide's files when you make a release.

**Describe alternatives you've considered**
There may be alternatives to versioneer, but I'm not familiar with them.

**Additional context**
I use versioneer in projects that I've contributed to, such as NiMARE. It would require [versioneer.py](https://github.com/neurostuff/NiMARE/blob/a5e8ea8c79e20de3c21deaf81e008c4a1e6dc367/versioneer.py), [rapidtide/_version.py](https://github.com/neurostuff/NiMARE/blob/a5e8ea8c79e20de3c21deaf81e008c4a1e6dc367/nimare/_version.py), and some edits to rapidtide/version.py (see [NiMARE/nimare/info.py](https://github.com/neurostuff/NiMARE/blob/a5e8ea8c79e20de3c21deaf81e008c4a1e6dc367/nimare/info.py) for an example).

**Comment by bbfrederick** [comment]
This seems like a nice solution - I'm attempting to integrate it now.  I'll push it to the dev branch, and when it's working I'll port it back to master.

**Comment by bbfrederick** [comment]
Done in version 1.9.3
