### ISSUE TITLE
Build docs in CI

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#34]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would help when opening pull requests to be able to check over the documentation as it renders on RTD.

**Describe the solution you'd like**
I don't know if it's supported in Travis, but CircleCI makes it pretty easy to build docs as a workflow within the continuous integration. See [here](https://github.com/neurostuff/NiMARE/blob/e602f78fe3d52d5fb2cc558abfc0e16b0e1f0b37/.circleci/config.yml#L39-L55) for an example.

That example could also cover the Python version-specific tests with minimal changes.

**Describe alternatives you've considered**
There's an RTD integration that may work, but I couldn't get it to work on one of my projects, so I lean toward CircleCI's method.

**Additional context**
I'd be happy to open a PR for this.

**Comment by bbfrederick** [comment]
If you'd do a PR, that would be great, since I know nothing about that.  Would you suggest moving completely to CircleCI from Travis?  Travis has been failing for months (on tests that pass on my home machine, so I really have no idea why...).

**Comment by tsalo** [comment]
CircleCI works well for me across a few projects. Plus Travis doesn't support artifacts (files created by tests that can be accessed online) on pull requests., but CircleCI does.
