### ISSUE TITLE
Deploy package to PyPi

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#35]
**Is your feature request related to a problem? Please describe.**
It would be awesome to be able to install `rapidtide` with `pip install rapidtide`. It would also make it easier to include rapidtide as a dependency in other packages.

**Describe the solution you'd like**
I've used a CircleCI-based workflow that deploys to PyPi whenever there's a new release, as part of CI (see [here](https://github.com/neurostuff/NiMARE/blob/e602f78fe3d52d5fb2cc558abfc0e16b0e1f0b37/.circleci/config.yml#L92-L112)). The only caveats that I'm aware of are (1) using Release Drafter-generated release drafts directly won't trigger the deploy workflow and (2) it _may_ require that only one user make releases for the repository. I don't think either restriction is an issue for this repo though.

The workflow requires the following:
1. Repo set up on CircleCI.
2. CircleCI config file with deployment workflow.
3. PyPi account.
4. PyPi username and password as private environmental variables in the CircleCI repo account.
5. Possibly repository set up on PyPi before auto deployment is started.
    - I adopted this workflow _after_ having released to PyPi a few times before, so it might require the package to already be listed.
6. Make release on GitHub with a name that matches the pattern in the CircleCI config.

**Describe alternatives you've considered**
You could push manually, but that's a lot of effort.

**Additional context**
If you're comfortable switching to CircleCI, I could help with this and #34 by working on the CircleCI configuration file.

**Comment by bbfrederick** [comment]
I would appreciate any help moving this to CircleCI.  I've found Travis fairly troublesome lately...

**Comment by tsalo** [comment]
Some good news. In [`tedana`](https://github.com/ME-ICA/tedana), we just switched to the "Publish Python Package" GitHub Action, and it's super easy! You just need to (1) sign up for a PyPi account, (2) add your PyPi username and password as secret variables in your repository's settings, (3) set up the publishing Action (the only thing we had to change was the Python version), and (4) make releases. It's easier than the CircleCI-based way.

I think I can open a PR to add the Action and remove the deploy step in your CI if you'd like. You'd still need to sign up for PyPi and add your username and password as secrets in the repo settings though.

**Comment by bbfrederick** [comment]
Ok, I think I've done that.  Does this also mean people will have the option of just installing rapidtide using "pip install rapidtide"?  That would be great.

**Comment by tsalo** [comment]
> Ok, I think I've done that.

Awesome. I'll try to open a PR for the other part later today.

> Does this also mean people will have the option of just installing rapidtide using "pip install rapidtide"?

Exactly!

**Comment by tsalo** [comment]
It looks like the Action failed (see [here](https://github.com/bbfrederick/rapidtide/runs/1955109177?check_suite_focus=true)). Here's the error message:

>HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
>Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
>Error: Process completed with exit code 1.

It looks like it could be a problem with the secret keys you added, but I'm not sure...

**Comment by tsalo** [comment]
Actually, based on the first error message, the problem might be that this workflow only works on existing PyPi packages, so you may need to publish it on PyPi manually first, and then the Action can take over from there...

**Comment by bbfrederick** [comment]
How would I do that?  And would I have to do that separately for the master and dev versions?  On that point - I'm starting to think that it's probably past time to merge dev into the master branch and just be done with it...

**Comment by tsalo** [comment]
>How would I do that?

I think the best approach is to follow the steps outlined at https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives on your local machine, from "Generating Distribution Archives" to the end.

>And would I have to do that separately for the master and dev versions?

I don't think you will need to do it separately for the two branches, as long as the contents of files like `setup.py`, `setup.cfg`, etc. are equivalent.

> On that point - I'm starting to think that it's probably past time to merge dev into the master branch and just be done with it...

I fully support this for selfish reasons, but I don't think it's a problem for this particular issue.

**Comment by tsalo** [comment]
I've actually done this a couple of times. I could upload the package to PyPi, add you as the maintainer, and you could remove me after? Then, the Action should work from there.

**Comment by bbfrederick** [comment]
If you don't mind, that would be great.  I took a look at the instructions and it seems kind of complicated...

**Comment by tsalo** [comment]
Okay, here's what I did (for posterity):

1. Downloaded the 1.9.3 release as zip.
2. `python -m build`, which created the `dist/` folder.
3. Created an API token for TestPyPi.
4. `python -m twine upload --repository testpypi dist/*` from the downloaded code folder.
    1. Username is `__token__`.
    2. Password is the token.
5. This failed. Too big.
6. Dropped tests from packaging (setup.py), from MANIFEST.in, and used setup.cfg to specify data folders instead of `package_data` (this is what I use in NiMARE and I figured it was worth a shot).
7. Deleted the rapidtide-egg.info folder that had been created.
8. `python -m build`. Now the dist files are reasonably sized (~30 MB each).
8. `python -m twine upload --repository testpypi dist/*`
9. Success!
10. `python -m twine upload` to upload to PyPi.

I am going to open a PR with the changes I think are necessary to reduce `rapidtide`'s package size enough to be uploadable to PyPi. I've also invited you as an owner on the PyPi package.

**Comment by tsalo** [comment]
Now that #61 is merged, I _think_ that releases from `master` should deploy without issue (🤞), but the changes will need to be propagated to `dev` before 2.0.X releases will work. I think this issue can be closed as well, but if deployment fails please let me know and I can try to help.

**Comment by bbfrederick** [comment]
I got 2.0alpha18 to successfully deploy - hooray!

**Comment by tsalo** [comment]
:tada: That's awesome! I'll close this issue then.
