### ISSUE TITLE
ReadTheDocs build failing on dev branch

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#44]
**Describe the bug**
The `dev` branch is failing to build on ReadTheDocs (see [this failed build](https://readthedocs.org/projects/rapidtide/builds/12173674/), for example).

**To Reproduce**
1. Push to `dev`
2. Check ReadTheDocs for triggered build
3. Check associated build's report

**Expected behavior**
The `dev` branch on ReadTheDocs would be up-to-date with the current code if it built.

**Screenshots**
![image](https://user-images.githubusercontent.com/8228902/97125538-acbb4d00-170a-11eb-929f-2428807cd05d.png)

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

I think I've successfully dealt with the problems locally, and would be happy to open a pull request to address this.

**Comment by bbfrederick** [comment]
Please do!  I was moving files around, and didn't notice this...

**Comment by tsalo** [comment]
Okay, can do. I will just wait until the `usage.rst`/`candidate_usage.md` is solidified, so I don't edit anything that's going to be removed.

**Comment by tsalo** [comment]
Not really sure why this wasn't closed automatically by #45, but the build was successful so I'm closing it now.
