### ISSUE TITLE
Install.md/usage

### ISSUE THREAD

**Issue by irebollo** [bbfrederick/rapidtide#5]
Examples is twice

rapidtide2 rapidtide/data/examples/examples/src/fmri.nii.gz rapidtide/data/examples/examples/dst/dgsr -L -r -15,15 --refinepasses=3
should be
rapidtide2 rapidtide/data/examples/src/fmri.nii.gz rapidtide/data/examples/dst/dgsr -L -r -15,15 --refinepasses=3

Promise to be a great tool! ;)

**Comment by bbfrederick** [comment]
That doesn't sound good, but I can't find it - which file are you looking at?

Welcome aboard!
