### ISSUE TITLE
Consider enabling Discussions feature for support

### ISSUE THREAD

**Issue by tsalo** [bbfrederick/rapidtide#52]
**Is your feature request related to a problem? Please describe.**
It's not a problem, _per se_, but support is currently theoretically done on NeuroStars. However, so far the only two questions ([here](https://neurostars.org/t/rapidtide-usage-with-corresponding-physio-data/16298) and [here](https://neurostars.org/t/automated-methods-to-segment-dural-venous-sinuses/16372)) have come from me, so perhaps `rapidtide` users have not adopted NeuroStars as much as one would hope.

**Describe the solution you'd like**
GitHub has a new [Discussions feature](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) that can serve as a more forum-like space for discussions that do not merit issues (e.g., usage questions). While it lacks the community of NeuroStars, it may be easier to keep track of.

**Describe alternatives you've considered**
The most obvious alternative is to continue to use NeuroStars. For more informal discussions, Gitter or creating a `rapidtide` channel in the BrainHack Mattermost might be good.

**Additional context**
None.

**Comment by tsalo** [comment]
Alternatively, it looks like you can add an issue template config file so that the issue template choice page users see when they open a new issue contains a link to NeuroStars for usage questions. I'd be happy to open a PR with the change.

**Comment by bbfrederick** [comment]
Please do. Sounds like a good idea.

**Comment by tsalo** [comment]
Cool! Since you're planning to overwrite `master` with `dev` in the future, I've opened duplicate PRs to both branches.
