### ISSUE TITLE
Python Install line error

### ISSUE THREAD

**Issue by jmatthews-rotman** [bbfrederick/rapidtide#62]
**Describe the bug**
One of my IT staff is trying to install this package on our server for us and is encountering a bug he wanted me to ask about. He is getting an error at the python install line, copied below. The server is running rhel 7, with python 3.7 and anaconda 3. 

**To Reproduce**
Here is the error from the python install line:

```
(base) [root@vm-ITDS3 rapidtide-master]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    f.write(date)
  File "/software/anaconda3/lib/python3.7/codecs.py", line 721, in write
    return self.writer.write(data)
  File "/software/anaconda3/lib/python3.7/codecs.py", line 377, in write
    data, consumed = self.encode(object, self.errors)
TypeError: utf_8_encode() argument 1 must be str, not None
```

**Comment by tsalo** [comment]
@bbfrederick I think that `date = versioneer.get_versions()["date"]` returns None, and to deploy to PyPi I actually had to drop that part from `setup.py`, but I forgot to include it in #61 😬. I don't know how important the DATE file is, but removing it from `setup.py` in both master and dev might fix this issue.

**Comment by bbfrederick** [comment]
Ok, I've updated the master branch to eliminate those lines from setup.py, and it seems to install correctly.  I  also made a new tag - 1.9.4 to incorporate all the changes we've made of late.  Taylor - how do I push an updated version to pypi?

**Comment by tsalo** [comment]
The Action was triggered, but it failed: https://github.com/bbfrederick/rapidtide/runs/2134215207?check_suite_focus=true

Given that the project exists on PyPi and you are the owner of the project there, the only thing I can guess is that the authentication info (PYPI_USERNAME and PYPI_PASSWORD) in the GitHub secret keys for this repository are wrong somehow.

**Comment by bbfrederick** [comment]
Figured it out (after trying everything else, including enabling 2FA)!

The script was looking for these:
 TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }} 
 TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }} 

But the secrets I had were:
PYPI_ACCOUNT_NAME
PYPI_ACCOUNT_PASSWORD

Deleted them and created ones with the correct names, and all is well.

**Comment by jmatthews-rotman** [comment]
Thank you @tsalo. This fix worked for my IT guy.
