### ISSUE TITLE
-d/dt fMRI signal for BOLD-CSF inflow coupling analysis

### ISSUE THREAD

**Issue by robbwh** [bbfrederick/rapidtide#67]
Any chance there could be support for taking the negative derivative of the fMRI signal (i.e., -np.gradient(timecourse)) after the filtering that rapidtide performs and using that as the fMRI timecourse data? 

I ask because of this [pre-print](https://www.biorxiv.org/content/10.1101/2021.03.29.437406v1.full) 

I've already gotten global grey matter BOLD - CSF coupling (somewhat similarly as they have in this other [pre-print](https://www.biorxiv.org/content/10.1101/2020.06.04.134726v1.full )):

Which worked, but I think it would be good to get time/MCCC at each voxel rather than just the single values.  
(BTW, doing the above made me appreciate rapidtide! Had to do the gaussian peak fitting myself...haha.) 

Anyway, I've already extracted the CSF inflow signal from the bottom fMRI slice, which would I have as an unfiltered probe regressor to give to rapidtide. 

So my proposed call to rapidtide could be something like:

rapidtide indata outdata --noglm --similaritymetric="correlation" --searchrange -20 20 --nofitfilt --oversampfac 5 --spatialfilt 3 --filterfreqs 0.005 0.05 --passes 1 --regressor="$csfinflowprobe" **--negativederivative**

Is this within the scope of rapidtide to implement? Thanks either way!

**Comment by bbfrederick** [comment]
Added to 2.0alpha24.  Please let me know how it works!

**Comment by robbwh** [comment]
Thanks a bunch for the addition! I think there's a minor bug in helper_classes.py where you're taking the negative gradient. 
I think -np.gradient should be inside the corrnormalize function.  

Correlations were extremely low when I first ran it, changing that seemed to fix it. 

I'll throw some data below but no need to look at it--only if you're interested to see how it turned out.

**Comment by robbwh** [comment]
From my earlier analysis:
Blue is -np.gradient(global grey matter) 
Orange is csf inflow signal from bottom slice of fmri
 ![image](https://user-images.githubusercontent.com/39274562/114805007-da06c080-9d67-11eb-856b-670608156250.png)


Here are the results from the rapidtide run. Prob need to tinker a little bit but looks a bit like the preprint: 
<img width="1555" alt="Screen Shot 2021-04-14 at 9 22 05 PM" src="https://user-images.githubusercontent.com/39274562/114804775-78deed00-9d67-11eb-8cca-1b587760ac5b.png">

**Comment by bbfrederick** [comment]
Whoops!  I had intended for the gradient to be inside the normalization - but it sure wasn't.  Fixed in the latest push, if you're syncing directly with the dev branch.  I'll have a new release within the next few days, and it will be in there.

The data look interesting, and well correlated - what do the maxcorr maps look like?  Also, do you expect some voxels to be negatively correlated with the csf flow?  If so you can use the --bipolar flag on the command line to pick to correlation of the largest magnitude, regardless of sign.

**Comment by robbwh** [comment]
Yes they are strikingly correlated--although I did pick a subject with very high grey matter BOLD-CSF coupling as a first test.

The timing is delayed and/or less plausible in a few subjects (working with a cohort of older with mixed cognitive statuses, which could be to blame though), and still haven't reviewed enough to decide if I should tinker with the settings. 

Here is the maxcorrmap for that subject. Doesn't look like too many negative MCCCs at all. I wouldn't expect negative MCCCs per se, (my hypothesis expects lower MCCCs in some subjects, but but negative MCCCs), but I'll keep an eye out for that, as anything is possible, though. 

<img width="1621" alt="Screen Shot 2021-04-18 at 9 14 42 PM" src="https://user-images.githubusercontent.com/39274562/115173230-742e7780-a08c-11eb-9354-e88549fedd77.png">

**Comment by robbwh** [comment]
Results are actually looking quite good now...thanks a bunch for this addition!

**Comment by loneblues** [comment]
> Added to 2.0alpha24. Please let me know how it works!

Hi! 

Is it possible that you add this functionality to showxcorrx? 
Thanks in advance! 
A lot of publications have cross correlation between negative derivative of gray matter BOLD signal and CSF, and I think showxcorrx is a great way to produce these figures! 

![Image](https://github.com/user-attachments/assets/80b4c9aa-9e73-438d-aed5-fd28a5ba8344)
