### ISSUE TITLE
"rapidtide2 is a rapidtide script, but is not installed" after Docker installation 

### ISSUE THREAD

**Issue by s-peu5** [bbfrederick/rapidtide#69]
Hi everybody
After following the guide for installing rapidtide (docker installation), when I try to run rapidtide2 through the docker I receive the message "rapidtide2 is a rapidtide script, but is not installed". I'm not very practical of using docker. Did I miss something? I installed the latest version with the tag :latest. I'm using Ubuntu 18.04.4 LTS
Thank you

**Comment by s-peu5** [comment]
> The "latest" container follows the development branch (currently 2.0alpha26), and it uses a slightly different calling syntax. Try your command again, but replace "rapidtide2" with "rapidtide2x_legacy", which uses the old calling syntax. Alternatively, when you download the docker container, you could specify "1.9.4" instead of "latest".
> 
> Let me know if that works.

Hi, thank you very much for answering. If I try to download versions 1.9.4, 1.9.3 or 1.9.2 I get the message
"Error response from daemon: manifest for fredericklab/rapidtide:1.9.4 not found: manifest unknown: manifest unknown"
While with 1.9.0 or 1.9.1 it works properly. Any hint on that?

**Comment by s-peu5** [comment]
Anyway, with version 1.9.1 my command runs correctly, so thank you for solving the first issue. Please let me know if you have any clue on why I couldn't download version 1.9.4

**Comment by s-peu5** [comment]
Hi @bbfrederick , thank you for fixing this!
Now, I'm able to run v1.9.5 properly, but I'm getting an error after the "Time lag estimation pass 2".
The command was
rapidtide2 /data_in/$in_ds /data_out/$out_ds -N 0 -r -10,60 -F 0.0,0.2 --lagmaxthresh=40 --ampthresh=0.2 --includemask=/mask_in/$mask --noglm --nofitfilt --regressor=/reg_in/$text_file_reg --regressorfreq=100

The last lines printed on stdin are

Time lag estimation pass 2
Percent complete: [                                                            ]
...
Percent complete: [############################################################] 100.000%
Correlation fitted in 230918 voxels
	ampfails= 0 
	lagfails= 0 
	widthfail= 0 
	edgefail= 0 
	fitfail= 0
Garbage collector: collected 0 objects.
rereading /data_in/***.nii  for GLM filter, please wait
done
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/rapidtide2", line 4, in <module>
    __import__('pkg_resources').run_script('rapidtide==0+unknown', 'rapidtide2')
  File "/usr/local/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/miniconda/lib/python3.7/site-packages/rapidtide-0+unknown-py3.7.egg/EGG-INFO/scripts/rapidtide2", line 3348, in <module>
    main()
  File "/usr/local/miniconda/lib/python3.7/site-packages/rapidtide-0+unknown-py3.7.egg/EGG-INFO/scripts/rapidtide2", line 3339, in main
    ")",
TypeError: sequence item 4: expected str instance, NoneType found


Any guess?

**Comment by bbfrederick** [comment]
This is a nightmare.  I'm not sure exactly why this is so hard to fix - I think it's some weird combination of Docker, git, and versioneer not wanting to play well together.  That said, I THINK things are fixed now in 1.9.6.  Let me know if that's true...

**Comment by s-peu5** [comment]
Thank you, version 1.9.6 is working! Great job!
