### ISSUE TITLE
--norefinedespeckled timeshift applied to negative number of voxels

### ISSUE THREAD

**Issue by robbwh** [bbfrederick/rapidtide#78]
When using the argument ```--norefinedespeckled```

Rapidtide tries to apply the timeshift to a negative number of voxels and refinement fails.
```
Percent complete: [############################################################] 100.00%refinement failed - terminating at end of pass 1
rereading /data/h_vmac/ahmedha/cvr_despike/data/234873/080/reactivity_preproc/epi_folder/mc_stc_despike_taskBlock_234873_epi.nii.gz to calculate mean value, please wait
done

performing pca refinement with pcacomponents set to 0.8
Using  7  component(s), accounting for  81.40% of the variance
pca/avg correlation =  -1.0

Timeshift applied to -14136 voxels, 21209 used for refinement: 
	 410476  locationfails 
	 380532  ampfails 
	 179507  lagfails 
	 409757  sigmafails
```

Is that just indicating most of my voxels are being despeckled? I'm confused why the number of voxels would be negative. 

Thanks and sorry for two posts in such quick succession.

**Comment by bbfrederick** [comment]
Uh, whoops?  That didn't show up in testing. I'll look at it tomorrow. Probably don't use that for the time being - using the despeckled voxels in refinement is the default (and previous) behavior.

**Comment by robbwh** [comment]
Okay, thank you. 

The reason I tried that argument was because when I used rapidtide 2.1.0 (docker container) 

```showtc output_desc-refinedmovingregressor_timeseries.json```

Looked more like I expected it to. 

<img width="645" alt="Screen Shot 2022-03-14 at 10 17 20 AM" src="https://user-images.githubusercontent.com/39274562/158203138-f91f8c7a-5340-4379-9a1b-6c95a3bd7437.png">


But using the newest version 2.2.0 it looked (maybe) not as good

<img width="644" alt="Screen Shot 2022-03-14 at 10 17 51 AM" src="https://user-images.githubusercontent.com/39274562/158203232-351d2bec-3847-41a9-875c-de4cdd9a34c6.png">

**Comment by robbwh** [comment]
sounds good, thanks!
