### ISSUE TITLE
When running, report the current version number.

### ISSUE THREAD

**Issue by dmd** [bbfrederick/rapidtide#91]
Please report version number in the log at startup.

**Comment by dmd** [comment]
I suspect this may require #96 to be resolved first.

**Comment by bbfrederick** [comment]
release_version, git_date, git_isdirty, git_longtag, and python_version are already all in the XXX_desc-runoptions_info.json file.  Or do you want it output to the console?

**Comment by dmd** [comment]
Yes, console is useful when looking at the logs... as long as it actually works (see #96).
